name: Test dev deployment
on: [push, pull_request]

jobs:
  build-publish:
    # Run on merge to main, where the commit name starts with "Bump version:" (for bump2version)
#    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      # used for generating API
      SM_DOCKER: samplemetadata:dev
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: buildenv
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          python-version: 3.7

      - name: "setup build env"
        run: |
          conda install pip conda-build anaconda-client requests
          pip install openapi-generator-cli

      - name: "build image"
        run: |
          docker build --tag $SM_DOCKER -f deploy/api/Dockerfile .

      - name: "build deployable API"
        run: |
          python regenerate_api.py
          ls -lGh sample_metadata
          pip install .

      - name: "Run unit tests"
        run: |
          python -m unittest discover test/
